name: Build and Release CI

on:
  push:
    branches:
    - master
    - bugfix/**
    - feature/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install Dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript

    - name: Run Tests
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm run test-ci

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  image-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Export to Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: gui:latest
        outputs: type=docker,dest=/tmp/gui.tar

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: gui:latest
        format: sarif
        output: trivy-results.sarif
        severity: 'CRITICAL,HIGH'

    - name: Upload GUI Image
      uses: actions/upload-artifact@v3
      with:
        name: gui-image
        path: /tmp/gui.tar
        retention-days: 5

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
    - test
    - image-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Version
      id: prep
      run: |
        echo ::set-output name=repository::$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download GUI Image
      uses: actions/download-artifact@v3
      with:
        name: gui-image
        path: /tmp

    - name: Load GUI Image
      run: docker load --input /tmp/gui.tar

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ghcr.io/${{ steps.prep.outputs.repository }}:${{ steps.prep.outputs.version }}
          ghcr.io/${{ steps.prep.outputs.repository }}:latest
        push: true
